# Generated by Django 3.0.6 on 2020-06-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='姓名', max_length=40)),
                ('idcard', models.CharField(help_text='身份证号', max_length=18)),
                ('phone', models.CharField(help_text='手机号', max_length=11, unique=True)),
                ('email', models.EmailField(help_text='邮箱', max_length=255)),
                ('age', models.IntegerField(help_text='姓名')),
                ('address', models.CharField(blank=True, help_text='地址', max_length=255, null=True)),
                ('updatetime', models.DateTimeField(auto_now=True, help_text='修改时间')),
                ('createtime', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
